/**
 * CSP Nonce Helper for React Components
 * 
 * Provides access to the CSP nonce generated by middleware
 * for inline scripts and styles.
 */

import { headers } from 'next/headers'

/**
 * Get CSP nonce from request headers (Server Components)
 */
export async function getNonce(): Promise<string> {
  const headersList = await headers()
  return headersList.get('x-nonce') || ''
}

/**
 * Get CSP nonce synchronously (for Client Components via props)
 * 
 * Usage in Server Component:
 * ```tsx
 * import { getNonce } from '@/lib/nonce'
 * 
 * export default async function Page() {
 *   const nonce = await getNonce()
 *   return <ClientComponent nonce={nonce} />
 * }
 * ```
 * 
 * Usage in Client Component:
 * ```tsx
 * 'use client'
 * 
 * export function ClientComponent({ nonce }: { nonce: string }) {
 *   return (
 *     <script nonce={nonce}>
 *       console.log('This inline script is CSP-compliant')
 *     </script>
 *   )
 * }
 * ```
 */

/**
 * ScriptWithNonce component for inline scripts
 * 
 * Usage:
 * ```tsx
 * import { ScriptWithNonce } from '@/lib/nonce'
 * 
 * export default async function Page() {
 *   return (
 *     <ScriptWithNonce>
 *       {`console.log('This script has a nonce')`}
 *     </ScriptWithNonce>
 *   )
 * }
 * ```
 */
export async function ScriptWithNonce({ children }: { children: string }) {
  const nonce = await getNonce()
  
  return (
    <script
      nonce={nonce}
      dangerouslySetInnerHTML={{ __html: children }}
    />
  )
}

/**
 * StyleWithNonce component for inline styles
 * 
 * Usage:
 * ```tsx
 * import { StyleWithNonce } from '@/lib/nonce'
 * 
 * export default async function Page() {
 *   return (
 *     <StyleWithNonce>
 *       {`.custom-class { color: red; }`}
 *     </StyleWithNonce>
 *   )
 * }
 * ```
 */
export async function StyleWithNonce({ children }: { children: string }) {
  const nonce = await getNonce()
  
  return (
    <style
      nonce={nonce}
      dangerouslySetInnerHTML={{ __html: children }}
    />
  )
}

/**
 * Example: Google Analytics with CSP nonce
 * 
 * Usage:
 * ```tsx
 * import { GoogleAnalyticsScript } from '@/lib/nonce'
 * 
 * export default async function RootLayout({ children }) {
 *   return (
 *     <html>
 *       <head>
 *         <GoogleAnalyticsScript measurementId="G-XXXXXXXXXX" />
 *       </head>
 *       <body>{children}</body>
 *     </html>
 *   )
 * }
 * ```
 */
export async function GoogleAnalyticsScript({ measurementId }: { measurementId: string }) {
  const nonce = await getNonce()
  
  if (!measurementId || process.env.NODE_ENV !== 'production') {
    return null
  }
  
  return (
    <>
      <script
        async
        src={`https://www.googletagmanager.com/gtag/js?id=${measurementId}`}
        nonce={nonce}
      />
      <script
        nonce={nonce}
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${measurementId}', {
              page_path: window.location.pathname,
            });
          `,
        }}
      />
    </>
  )
}

/**
 * Example: Stripe.js with CSP nonce
 * 
 * Note: Stripe.js script is loaded externally, but if you need
 * inline initialization code, use this pattern.
 */
export async function StripeScript({ publishableKey }: { publishableKey: string }) {
  const nonce = await getNonce()
  
  if (!publishableKey) {
    return null
  }
  
  return (
    <>
      <script
        src="https://js.stripe.com/v3/"
        nonce={nonce}
      />
      <script
        nonce={nonce}
        dangerouslySetInnerHTML={{
          __html: `
            window.stripePublishableKey = '${publishableKey}';
          `,
        }}
      />
    </>
  )
}
